### ISSUE TITLE
Error looking up beamcode table for fictional radars

### ISSUE THREAD

**Issue by ljlamarche** [amisr/amisrsynthdata#11]
When a non-standard radar is listed under radar abbreviation (not PFISR, RISR-N, or RISR-C), the code crashes with the following error because it can't find the appropriate beamcode file, even if no beamcodes are listed to use.
```
Traceback (most recent call last):
  File "/Users/e30737/miniconda3/envs/synthdata/bin/amisrsynthdata", line 8, in <module>
    sys.exit(main())
  File "/Users/e30737/Desktop/Projects/AMISR/amisrsynthdata/src/amisrsynthdata/syntheticdata.py", line 742, in main
    sd = SyntheticData(config)
  File "/Users/e30737/Desktop/Projects/AMISR/amisrsynthdata/src/amisrsynthdata/syntheticdata.py", line 35, in __init__
    self.radar = Radar(config)
  File "/Users/e30737/Desktop/Projects/AMISR/amisrsynthdata/src/amisrsynthdata/radar.py", line 33, in __init__
    beam_az1, beam_el1, beam_ksys1 = self.beams_from_beam_codes(beam_bc1)
  File "/Users/e30737/Desktop/Projects/AMISR/amisrsynthdata/src/amisrsynthdata/radar.py", line 91, in beams_from_beam_codes
    bc_data = np.loadtxt(bc_file)
  File "/Users/e30737/miniconda3/envs/synthdata/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Users/e30737/miniconda3/envs/synthdata/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/Users/e30737/miniconda3/envs/synthdata/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /Users/e30737/Desktop/Projects/AMISR/amisrsynthdata/src/amisrsynthdata/beamcodes/bcotable_eiscat.txt not found.
```

**Comment by ljlamarche** [comment]
Fixed in df9d376569929c0d2cd7c3c0bcff0bae053b1a9b.
